#!/usr/bin/env python3
"""Turn a firmware blob into a C array for file-system-less ports."""
import sys

def main():
    blob, name, out = sys.argv[1], sys.argv[2], sys.argv[3]
    data = open(blob, 'rb').read()
    with open(out, 'w') as f:
        f.write('/* Generated by scripts/gen_firmware_array.py - do not edit. */\n')
        f.write('#include <stdint.h>\n#include <stddef.h>\n\n')
        f.write('const uint8_t %s_data[] = {\n' % name)
        for i in range(0, len(data), 16):
            row = data[i:i+16]
            f.write('\t' + ' '.join('0x%02x,' % b for b in row) + '\n')
        f.write('};\n')
        f.write('const size_t %s_size = sizeof(%s_data);\n' % (name, name))

if __name__ == '__main__':
    main()
