/*
 * sdkconfig.h - effective standalone-SDK configuration for the RK3568
 * FreeRTOS test system.
 *
 * Values mirror the lab SDK's verified rk3568_aarch64_el1_itx_shell /
 * _wlan configs (see README.md). The copied SDK sources consume these via
 * #include "sdkconfig.h"; do not trim entries without grepping consumers.
 */

#ifndef SDK_CONFIG_H__
#define SDK_CONFIG_H__

#define CONFIG_USE_FREERTOS

/* Arch configuration */

#define CONFIG_TARGET_ARMv8
#define CONFIG_ARCH_NAME "armv8"
#define CONFIG_ARCH_ARMV8_AARCH64
#define CONFIG_ARCH_ARMV8_0_A

/* Compiler configuration */

#define CONFIG_ARM_GCC_SELECT
#define CONFIG_TOOLCHAIN_NAME "gcc"
#define CONFIG_TARGET_ARMV8_AARCH64
#define CONFIG_ARCH_EXECUTION_STATE "aarch64"
#define CONFIG_BOOT_WITH_FLUSH_CACHE
/* CONFIG_MMU_DEBUG_PRINTS is not set */

/* CONFIG_USE_MSDF is not set */
#define CONFIG_MMU_PAGE_SIZE_4K
#define CONFIG_MMU_PAGE_SIZE 0x1000
/* CONFIG_USE_EL2 is not set */
#define CONFIG_MAX_XLAT_TABLES 256
#define CONFIG_ENABLE_GIC_ITS
/* CONFIG_ENABLE_GDB_STUB is not set */
/* CONFIG_ENABLE_FREBOOT is not set */

/* Soc configuration */

#define CONFIG_TARGET_RK3568
#define CONFIG_SOC_NAME "rk3568"
#define CONFIG_SOC_CORE_NUM 4
#define CONFIG_F32BIT_MEMORY_ADDRESS 0x00000000
#define CONFIG_F32BIT_MEMORY_LENGTH 0x100000000
#define CONFIG_F64BIT_MEMORY_ADDRESS 0x00000000
#define CONFIG_F64BIT_MEMORY_LENGTH 0x100000000
#define CONFIG_DEFAULT_DEBUG_PRINT_UART2
/* CONFIG_UART_INIT_NOT_CLR_INTR is not set */

/* Board configuration */

#define CONFIG_BOARD_NAME "itx"
#define CONFIG_RK3568_ITX_BOARD
#define CONFIG_TARGET_NAME "net80211"

/* Sdk common configuration */

#define CONFIG_ELOG_LINE_BUF_SIZE 0x100
#define CONFIG_LOG_ERROR
/* CONFIG_USE_PHYSICAL_GTIMER is not set */
#define CONFIG_USE_VIRTUAL_GTIMER
#define CONFIG_USE_DEFAULT_INTERRUPT_CONFIG
#define CONFIG_INTERRUPT_ROLE_MASTER

/* Drivers configuration */

#define CONFIG_USE_SERIAL

/* Linker options */

#define CONFIG_IMAGE_LOAD_ADDRESS 0x0a000000
#define CONFIG_IMAGE_MAX_LENGTH 0x2000000
#define CONFIG_HEAP_SIZE 1
#define CONFIG_STACK_SIZE 0x10000

/* FreeRTOS kernel configuration */

#define CONFIG_FREERTOS_OPTIMIZED_SCHEDULER
#define CONFIG_FREERTOS_HZ 1000
/* CONFIG_NON_SECURE_PHYSICAL_TIMER is not set */
#define CONFIG_NON_SECURE_VIRTUAL_TIMER
#define CONFIG_FREERTOS_MAX_PRIORITIES 32
#define CONFIG_FREERTOS_KERNEL_INTERRUPT_PRIORITIES 13
#define CONFIG_FREERTOS_MAX_API_CALL_INTERRUPT_PRIORITIES 11
#define CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS 1
#define CONFIG_FREERTOS_MINIMAL_TASK_STACKSIZE 1024
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 32
#define CONFIG_FREERTOS_TIMER_TASK_PRIORITY 3
#define CONFIG_FREERTOS_TIMER_TASK_STACK_DEPTH 2048
#define CONFIG_FREERTOS_TIMER_QUEUE_LENGTH 10
#define CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE 0
#define CONFIG_FREERTOS_USE_TRACE_FACILITY
#define CONFIG_FREERTOS_TOTAL_HEAP_SIZE 10240
#define CONFIG_FREERTOS_TASK_FPU_SUPPORT 1

#endif
